services:
  - type: web
    name: hrm-location-tracker-api
    env: node
    region: singapore
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://hrmtracker:hrmtracker123@hrmtracker.mongodb.net/hrm-tracker?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: hrm_location_tracker_secret_key_2023
      - key: JWT_EXPIRE
        value: 30d

  - type: web
    name: hrm-location-tracker-web
    env: static
    region: singapore
    buildCommand: cd web-dashboard && npm install && npm run build
    staticPublishPath: web-dashboard/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production 