services:
  - type: web
    name: hrm-tracker-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: MONGO_URI
        fromDatabase:
          name: hrm-tracker-db
          property: connectionString

databases:
  - name: hrm-tracker-db
    plan: free 